### ISSUE TITLE
Add Senza version to /api/status endpoint

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando-stups/lizzy#173]
Would be nice to have the Senza version in the `/api/status` endpoint response. 

It is interesting to know which version in case there are bugs in Senza. So we know that we need to create a new Lizzy deployment image.

**Comment by LappleApple** [comment]
Hey @rafaelcaricio @jmcs, does this still seem desirable? If not, let's close.

**Comment by rafaelcaricio** [comment]
It is desirable.

**Comment by LappleApple** [comment]
@rafaelcaricio OK. Do you want to do it yourselves, or is a "Help Wanted" label OK to get contributions?
