### ISSUE TITLE
Add support for scaling stacks in Lizzy

### ISSUE THREAD

**Issue by elezar** [zalando-stups/lizzy#190]
When deploying a new stack, I would like to scale the stack to a similar number of instances to the current stack, before switching traffic to the stack. I would thus like to add support for scaling stacks to lizzy.

One proposal would be to add this to the `PATCH /stacks/{stack-id}` endpoint (the `GET /stacks/{stack-id}` endpoint would also need to be changed to return the required information).

**Comment by LappleApple** [comment]
Hi @jmcs and @rafaelcaricio: Looks like @elezar's issue didn't get a response. What do you think about his suggestion?

**Comment by elezar** [comment]
Thanks for following up on this @LappleApple.

We recently came across another use-case where scaling using lizzy would be useful.

**Comment by ovolynets** [comment]
I am also interested in this feature. Usecase: scale instances of the old stack down after successful deployment

**Comment by LappleApple** [comment]
Hey @elezar @ovolynets, @jmcs is open to InnerSourced PRs on this. Don't know if you have capacity, bu if you'd like to do this it would be great.

**Comment by elezar** [comment]
Yes, we have been talking about it a bit, but we do have some capacity issues at the moment. Will keep you posted.

**Comment by scherniavsky** [comment]
@jmcs do you think this can be closed now?

**Comment by elezar** [comment]
I'm closing the issue.
